version: '3'

services:
  redis-master:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.master
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./redis-master/redis-data:/data
    networks:
      my-network:
        ipv4_address: 172.28.1.2

  redis-replica-1:
    build:
      context: .
      dockerfile: Dockerfile.replica1
    container_name: redis-replica-1
    ports:
      - "6380:6379"
    volumes:
      - ./redis-replica-1/redis-data:/data
    networks:
      my-network:
        ipv4_address: 172.28.1.3

  redis-replica-2:
    build:
      context: .
      dockerfile: Dockerfile.replica2
    container_name: redis-replica-2
    ports:
      - "6381:6379"
    volumes:
      - ./redis-replica-2/redis-data:/data
    networks:
      my-network:
        ipv4_address: 172.28.1.4

  redis-sentinel-1:
    build:
      context: .
      dockerfile: Dockerfile.sentinel1
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    networks:
      my-network:
        ipv4_address: 172.28.1.5

  redis-sentinel-2:
    build:
      context: .
      dockerfile: Dockerfile.sentinel2
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    networks:
      my-network:
        ipv4_address: 172.28.1.6

  redis-sentinel-3:
    build:
      context: .
      dockerfile: Dockerfile.sentinel3
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    networks:
      my-network:
        ipv4_address: 172.28.1.7

networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
